# Generated by Django 5.1.4 on 2024-12-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_alter_course_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('birthDay', models.DateField()),
                ('code', models.CharField(max_length=12)),
                ('active', models.BooleanField()),
                ('courses', models.ManyToManyField(to='app_admin.course')),
            ],
        ),
    ]
